DEFAULT_EXCEL_FOLDER = r"E:\\casacas"

VARIACIONES_POR_CATEGORIA = {
    "prendas de cabeza": [
        "gorro", "gorros", "gorra", "gorras", "chullo", "chullos", "beanies", "pasamontana",
        "pasamontanas", "visera", "viseras", "parasoles", "parasoles", "viseras deportivas",
    ],
    "ropa y abrigo": [
        "casaca", "casacas", "chamarra", "chamarras", "camiseta", "camisetas", "cortavientos",
        "jackets", "chaqueta", "chaquetas", "blazer", "blazers",
        "parka", "parkas", "abrigos largos", "gabardina", "gabardinas",
        "abrigo", "abrigos", "sobretodo", "sobretodos", "prendas de invierno",
        "polera", "poleras", "sudadera", "sudaderas", "hoodie", "hoodies", "buzo",
        "buzos", "chaleco", "chalecos", "gilets", "chalecos tacticos",
        "polo", "polos", "remera", "remeras", "t-shirt", "t-shirts", "pantalon", "pantalones", "jean", "jeans", "denim", "short", "shorts", "bermuda",
    ],
    "textiles y hogar": [
        "toalla", "toallas", "toallones", "pano", "panos", "panos microfibra",
        "almohada", "almohadas", "almohadas de viaje", "cojin", "cojines",
        "mandil", "mandiles", "delantal", "delantales", "tabliers",
    ],
    "bolsos y transporte": [
        "mochila", "mochilas", "morral", "morrales", "morrales de espalda", "backpack",
        "backpacks", "canguro", "canguro", "canguros", "rinonera", "rinoneras", "koalas",
        "bolsa", "bolsas", "bolso", "bolsos", "bolsas ecologicas", "bolsos deportivos",
        "bolsos cruzados", "totes", "notex", "chimpunera", "chimpuneras", "portacalzado",
        "portacalzados", "bandolera", "bandoleras", "maletin", "maletines",
    ],
    "papeleria y oficina": [
        "cuaderno", "cuadernos", "anillado", "anillados", "espirales",
        "libreta", "libretas", "journals", "notepad", "notepads",
        "block", "blocks", "blocs de notas", "tacos de notas", "nota", "notas",
        "hoja", "hojas", "folio", "folios", "papel", "papeles",
        "agenda", "agendas", "planificadores", "diario", "diarios",
        "cuadernillo", "cuadernillos", "folleto", "folletos", "pasquines",
        "cartuchera", "cartucheras", "estuche", "estuches", "portautiles",
        "neceser", "neceseres", "bolsos de aseo", "organizadores",
        "lapicero", "lapiceros", "boligrafo", "boligrafos", "pluma", "plumas", "esferos",
        "resaltador", "resaltadores", "plumon", "plumones", "plumones fluor", "marcadores de texto",
        "tarjeta", "tarjetas", "tarjetas personales", "business cards",
        "porta nombre acrilico", "porta nombres acrilicos", "identificadores", "fotochecks",
        "porta nombre madera", "porta nombres madera", "identificadores rusticos",
        "porta post it calendario", "porta post it calendarios", "organizadores de escritorio",
    ],
    "accesorios y premiaciones": [
        "llavero", "llaveros", "pendientes", "keychains",
        "pin", "pines", "prendedores", "insignia", "insignias", "broche",
        "broches", "trofeo", "trofeos", "copa", "copas", "galardon",
        "galardones", "medalla", "medallas", "preseas", "condecoracion", "condecoraciones",
        "placa", "placas", "placas grabadas", "reconocimiento", "reconocimientos",
    ],
    "menaje y otros": [
        "tomatodo", "tomatodos", "botella", "botellas", "vino", "vinos",
        "caramanolas", "shakers", "vaso", "vasos", "vasos termicos",
        "copas", "copas", "taza", "tazas", "mugs", "pocillos",
        "cafetera", "cafeteras", "prensas francesas", "mokes",
        "cuchara", "cucharas", "cubiertos", "utensilios", "batidor",
        "batidores", "mezclador", "mezcladores", "espumadores", "sticker",
        "stickers", "calcomania", "calcomanias", "adhesivo", "adhesivos",
        "caja", "cajas", "empaques", "packaging", "cubo", "cubos", "dado",
        "dados", "bloque", "bloques", "alcancia", "alcancias", "huchas", "chanchitos",
        "pad mouse", "mouse pad", "mousepad", "alfombrillas", "tapetes de escritorio",
        "prop selfie", "props selfie", "accesorios para fotos", "marcos selfie",
        "tablet tent", "tablet tents", "habladores", "carpas de mesa", "displays",
        "kit", "power bank", "manta", "mantas", "pastillero", "pastilleros",
        "porta frasco", "exhibidor", "pasa diapositiva",
    ],
}

HOJAS_EXCLUIDAS = [
    "criterios",
    "tallas",
    "cronograma",
    "datos",
    "deuda",
    "produccion",
    "proveedor",
    "proveedores",
    "costo de proyecto",
]
